# The Folding@Home project values, you might want to overwrite user and team.
#
# It relies on the docker image by https://github.com/richarvey/FoldingAtHome.
# If you have your own user or team, override the values below. You can also
# enable/disable gpus, smp, etc.
foldingathome:
  image: linuxserver/foldingathome
  config:
    gpu: false
    gui-enabled: false
    disable-viz: true
    verbosity: 1
    # passkey: ""
    power: "full"
    smp: true
    team: 1064771
    user: "Rancher-ToU"
    command-allow-no-pass: ""
    web-allow: "0/0:7396"
    allow: "0/0:7396"
  env:
    PUID: "0"
    PGID: "0"
    TZ: "Etc/UTC"
  nodeSelector: {}
    # folding: "yes"
  priorityClassName: vlow-priority
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# Horizontal pod auto scaler configuration. The goal is to backfill the
# cluster with folding@home workloads, so we use an hpa resource with a very high
# number of max replicas (max replicas is currently mandatory).
#
# vlow-priority should be set to < -10, so that the cluster auto-scaler does
# not take them into account.
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: ${max_replicas}
  targetCPU: 60
  targetMemory: 60

# A set of predefined priorities for your cluster.
# If you can drop if you already manage priorities yourself, otherwise this
# will setup a default one and a very low priority which is used by the
# workloads (enabling preemption).
priority:
  - name: default-priority
    value: 100000
    default: true
  - name: vlow-priority
    value: -100000
