apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  labels:
    rke2-upgrade: agent
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 2
  cordon: true
  drain:
    force: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: NotIn
        values:
          - 'true'
  prepare:
    args:
      - prepare
      - server-plan
    image: rancher/rke2-upgrade
  serviceAccountName: system-upgrade
  tolerations:
    - effect: NoSchedule
      key: monitoring
      operator: Equal
      value: 'yes'
  upgrade:
    image: rancher/rke2-upgrade
  version: v1.27.6-rke2r1
